// Ops queue — items generated by tech visit observations.
//
// When a technician finishes a visit, they log two things:
//   1. What they did and whether it's fully resolved (captured in the visit log)
//   2. Anything office needs to act on — upsell opportunity, return visit needed,
//      recurring pattern that needs a structural fix, customer escalation
//
// The second category creates OpsQueueItems. These are not tech todos — the tech's
// job is done when they flag and leave. These are office todos: quote the ATO,
// schedule the return stop, call the account manager, adjust the service cadence.
//
// Pattern detection works the same way as knowledge-capture rule insight:
// accumulate observations, derive signal when sample size is meaningful,
// suggest an action. The difference is the output goes to an ops queue
// rather than a rule change recommendation.

import type { ServiceType } from "@/types/database";
import { FOLLOWUP_STALE_DAYS } from "./schedule";

// ─── Ops queue item ────────────────────────────────────────────────────────

export type OpsItemKind =
  | "upsell_opportunity"      // tech noticed something the customer might want — office quotes it
  | "return_visit_needed"     // work wasn't completable on this visit — office schedules return
  | "pattern_alert"           // same issue 3+ times — structural fix needed, not another band-aid
  | "customer_escalation"     // customer expressed a concern — account manager contacts them
  | "service_cadence_review"; // visit frequency may not match what the account actually needs

export type OpsItemPriority = "urgent" | "this_week" | "next_visit" | "whenever";
export type OpsItemStatus = "open" | "in_progress" | "resolved";

export interface OpsQueueItem {
  // Identity
  customer_id: string;
  visit_id: string;           // the visit that generated this item
  tech_id: string;
  flagged_at: string;         // ISO timestamp

  kind: OpsItemKind;
  priority: OpsItemPriority;
  status: OpsItemStatus;

  // What the tech observed and what they think should happen
  observation: string;        // what the tech saw or heard — in their own words
  suggested_action: string | null; // optional — tech's view on what office should do

  // For upsell_opportunity items — which product
  sku: string | null;

  // Resolution
  resolved_at: string | null;
  resolution_notes: string | null;
}

// ─── Follow-up outcome ─────────────────────────────────────────────────────
//
// Captured in the visit log when a tech closes out a visit. Replaces the
// binary followup_required yes/no with a structured outcome that tells office
// exactly what was done, what still needs to happen, and who owns it.

export type ResolutionStatus = "fully_resolved" | "partially_handled" | "could_not_fix";
export type NextStepOwner = "field" | "office" | "customer";

export interface VisitOutcome {
  visit_id: string;
  tech_id: string;
  customer_id: string;
  logged_at: string;

  // What the tech did — replaces the vague "issue found" field
  work_completed: string;
  resolution_status: ResolutionStatus;

  // What still needs to happen — only relevant when not fully_resolved
  next_step: string | null;
  next_step_owner: NextStepOwner | null;

  // Ops flag — optional, creates an OpsQueueItem if present
  ops_flag: Pick<OpsQueueItem, "kind" | "observation" | "suggested_action" | "sku"> | null;
}

// ─── Pattern detection ─────────────────────────────────────────────────────
//
// Accumulates visit observations per account and surfaces recurring issues
// once a threshold is crossed. The output is a suggested ops action, not
// just a count — the goal is to route the right response, not just flag
// that something is happening.

const MIN_OCCURRENCES_FOR_PATTERN = 3;
const PATTERN_LOOKBACK_DAYS = 180;  // 6 months — issues older than this are historical, not patterns

export interface RecurringPattern {
  issue: string;
  occurrences: number;
  last_seen: string;           // ISO date
  is_active_pattern: boolean;  // true = within lookback window and above threshold
  suggested_ops_action: string;
}

// Derives recurring patterns from a set of issue observations for one account.
// Each observation is { issue: string, seen_on: string (ISO date) }.
export function deriveRecurringPatterns(
  observations: Array<{ issue: string; seen_on: string }>
): RecurringPattern[] {
  const cutoff = new Date();
  cutoff.setDate(cutoff.getDate() - PATTERN_LOOKBACK_DAYS);

  // Count occurrences per issue within the lookback window
  const counts = new Map<string, { total: number; last_seen: string }>();
  for (const obs of observations) {
    const seen = new Date(obs.seen_on);
    const prev = counts.get(obs.issue);
    if (seen >= cutoff) {
      counts.set(obs.issue, {
        total: (prev?.total ?? 0) + 1,
        last_seen: prev ? (obs.seen_on > prev.last_seen ? obs.seen_on : prev.last_seen) : obs.seen_on,
      });
    }
  }

  return [...counts.entries()]
    .filter(([, { total }]) => total >= MIN_OCCURRENCES_FOR_PATTERN)
    .map(([issue, { total, last_seen }]) => ({
      issue,
      occurrences: total,
      last_seen,
      is_active_pattern: true,
      suggested_ops_action: suggestPatternAction(issue, total),
    }))
    .sort((a, b) => b.occurrences - a.occurrences);
}

function suggestPatternAction(issue: string, occurrences: number): string {
  const lower = issue.toLowerCase();
  if (lower.includes("top-off") || lower.includes("evaporation")) {
    return `Top-off issue has occurred ${occurrences} times in 6 months. Quote an ATO unit (EQUIP-ATO-001) — this will not resolve itself between visits.`;
  }
  if (lower.includes("filter sock") || lower.includes("sump")) {
    return `Filtration issue has occurred ${occurrences} times. Consider increasing service frequency or leaving a spare on site for the customer.`;
  }
  if (lower.includes("feeding") || lower.includes("staff")) {
    return `Staff behaviour pattern. Arrange a brief training session with the office manager — this needs a customer-side fix, not more tech visits.`;
  }
  if (lower.includes("access") || lower.includes("front desk")) {
    return `Access issue occurring repeatedly. Update access notes and confirm a direct contact at this site.`;
  }
  if (lower.includes("appearance") || lower.includes("event") || lower.includes("water clarity")) {
    return `Appearance concern triggered ${occurrences} times. Review whether current service cadence aligns with this account's event schedule.`;
  }
  return `Issue recurring ${occurrences} times in 6 months. Review with account manager — repeated band-aid fixes are not resolving the root cause.`;
}

// ─── Account service insight ───────────────────────────────────────────────
//
// Aggregated view of service health for one account.
// Surfaced to ops so they can act proactively rather than waiting for the
// next emergency rescue call or tech escalation.

export interface AccountServiceInsight {
  customer_id: string;

  // Recurring patterns — the things that keep coming back
  recurring_patterns: RecurringPattern[];
  has_active_patterns: boolean;

  // Follow-up health
  open_followup_count: number;
  stale_followup_count: number;         // open for > FOLLOWUP_STALE_DAYS

  // Ops queue
  open_ops_items: number;
  urgent_ops_items: number;

  // Service cadence signal
  current_service_type: ServiceType | null;
  cadence_suggestion: "increase" | "decrease" | "maintain" | null;
  cadence_reason: string | null;

  suggested_action: "escalate" | "review" | "monitor";
  suggested_action_reason: string;
}

export function deriveAccountServiceInsight(params: {
  customer_id: string;
  current_service_type: ServiceType | null;
  observations: Array<{ issue: string; seen_on: string }>;
  open_followups: Array<{ days_open: number }>;
  ops_items: OpsQueueItem[];
}): AccountServiceInsight {
  const { customer_id, current_service_type, observations, open_followups, ops_items } = params;

  const patterns = deriveRecurringPatterns(observations);
  const hasActivePatterns = patterns.some((p) => p.is_active_pattern);

  const staleFollowups = open_followups.filter((f) => f.days_open >= FOLLOWUP_STALE_DAYS);

  const openOpsItems = ops_items.filter((i) => i.status === "open");
  const urgentOpsItems = openOpsItems.filter((i) => i.priority === "urgent");

  // Cadence signal — derive from pattern frequency and service type
  let cadenceSuggestion: AccountServiceInsight["cadence_suggestion"] = "maintain";
  let cadenceReason: string | null = null;

  if (patterns.length >= 3 && current_service_type === "monthly_maintenance") {
    cadenceSuggestion = "increase";
    cadenceReason = `${patterns.length} recurring issues in the last 6 months on monthly cadence. Biweekly visits would catch these earlier.`;
  } else if (patterns.length === 0 && staleFollowups.length === 0 && current_service_type === "biweekly_maintenance") {
    cadenceSuggestion = "decrease";
    cadenceReason = "No recurring issues and no stale follow-ups on biweekly cadence. Monthly may be sufficient and would reduce cost.";
  }

  // Suggested action
  let suggested_action: AccountServiceInsight["suggested_action"] = "monitor";
  let suggested_action_reason = "No active patterns or stale follow-ups. Account is stable.";

  if (urgentOpsItems.length > 0 || staleFollowups.length >= 3) {
    suggested_action = "escalate";
    suggested_action_reason = urgentOpsItems.length > 0
      ? `${urgentOpsItems.length} urgent ops item(s) require immediate attention.`
      : `${staleFollowups.length} follow-ups have been open more than ${FOLLOWUP_STALE_DAYS} days without resolution.`;
  } else if (hasActivePatterns || openOpsItems.length > 0 || cadenceSuggestion !== "maintain") {
    suggested_action = "review";
    suggested_action_reason = hasActivePatterns
      ? `${patterns.length} recurring issue pattern(s) — root cause not yet addressed.`
      : openOpsItems.length > 0
      ? `${openOpsItems.length} open ops item(s) pending office action.`
      : cadenceReason ?? "Service cadence may need adjustment.";
  }

  return {
    customer_id,
    recurring_patterns: patterns,
    has_active_patterns: hasActivePatterns,
    open_followup_count: open_followups.length,
    stale_followup_count: staleFollowups.length,
    open_ops_items: openOpsItems.length,
    urgent_ops_items: urgentOpsItems.length,
    current_service_type,
    cadence_suggestion: cadenceSuggestion,
    cadence_reason: cadenceReason,
    suggested_action,
    suggested_action_reason,
  };
}

// ─── Queue helpers ─────────────────────────────────────────────────────────
//
// Sort and filter the ops queue for the office view.
// Priority order: urgent → this_week → next_visit → whenever.
// Within priority: oldest first (FIFO — don't let things age out silently).

const PRIORITY_ORDER: Record<OpsItemPriority, number> = {
  urgent: 0,
  this_week: 1,
  next_visit: 2,
  whenever: 3,
};

export function sortOpsQueue(items: OpsQueueItem[]): OpsQueueItem[] {
  return [...items].sort((a, b) => {
    const pa = PRIORITY_ORDER[a.priority];
    const pb = PRIORITY_ORDER[b.priority];
    if (pa !== pb) return pa - pb;
    return a.flagged_at.localeCompare(b.flagged_at);
  });
}

export function openOpsItems(items: OpsQueueItem[]): OpsQueueItem[] {
  return sortOpsQueue(items.filter((i) => i.status === "open"));
}
